services:
  redis:
    image: redis:7.0.5
    container_name: "redis-db"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass kcFjcdAaC7mfds5C

volumes:
  redis_data:
    driver: local